export class TestScript{
    id:number;
    testCaseID:string;
    tc_stepID: string;
    testScriptName: string;
    functionDescription: string;
    functionName: string;
    execute: string;
    param1: string;
    param2: string;
    param3: string;
    param4: string;
    param5: string;    
    param6: string;
    param7: string;
    param8: string;
    param9: string;
    param10: string;
    param11: string;
    param12: string;
    param13: string;
    param14: string;
    param15: string;
    param16: string;
    param17: string;
    param18: string;
    param19: string;
    param20: string;
    featureName: string;
}