export class Keywords {
    "functionName": string;
    "stepDescription": string;
    "actionOrKeyword": string;
    "objectLogicalName": string;
    "execute": string;
    "param1": string;
    "param2": string;
    "param3": string;
    "param4": string;
    "param5": string;
    "param6": string;
    "param7": string;
    "param8": string;
    "param9": string;
    "param10": string;
    "featureName": string;
    "statusID": number;
    "cudStatusID": number;
    "isLocked": boolean;
    "lockedByUser": number;
    "addedDate": string;
    "updateDate": string;
    "id": number;
  };
