export class Keywords {
    functionName: string; 
    stepDescription: string; 
    actionOrKeyword: string; 
    objectLogicalName: string; 
    run: string; 
    param1: string; 
    param2: string; 
    param3: string; 
    param4: string; 
    param5: string; 
    param6: string; 
    param7 : string; 
    param8: string; 
    param9: string; 
    param10: string; 
    param11: string; 
    param12: string; 
    param13: string; 
    param14: string; 
    param15: string; 
    param16: string; 
    param17 : string; 
    param18: string; 
    param19: string; 
    param20: string; 
    module: string;
    statusID: number;
    cudStatusID: number;
    isLocked: boolean;
    lockedByUser: number;
    createdOn: string;
    updatedOn: string;
    userId: number;
    id: number; 
  };
