export const keywordsColumns: any[] = [
    { label: 'ID', value: { field: 'id', header: 'ID'}},
    { label: 'Function Name', value: { field: 'functionName', header: 'Function Name'}},
    { label: 'Step Description', value: { field: 'stepDescription', header: 'Step Description'}},
    { label: 'Action or Keyword', value: { field: 'actionOrKeyword', header: 'Action or Keyword'}},
    { label: 'Object Logical Name', value: { field: 'objectLogicalName', header: 'Object Logical Name'}},
    { label: 'Run', value: { field: 'run', header: 'Run'}},
    { label: 'Module', value: { field: 'module', header: 'Module'}},
    { label: 'Status ID', value: { field: 'statusID', header: 'Status ID'}},
    { label: 'Cud Status ID', value: { field: 'cudStatusID', header: 'Cud Status ID'}},
    { label: 'Is Locked', value: { field: 'isLocked', header: 'Is Locked'}},
    { label: 'Locked By User', value: { field: 'lockedByUser', header: 'Locked By User'}},
    { label: 'Created On', value: { field: 'createdOn', header: 'Created On'}},
    { label: 'Updated On', value: { field: 'updatedOn', header: 'Updated On'}},
    { label: 'User ID', value: { field: 'userId', header: 'User ID'}},
    { label: 'Param 1', value: { field: 'param1', header: 'Param 1'}},
    { label: 'Param 2', value: { field: 'param2', header: 'Param 2'}},
    { label: 'Param 3', value: { field: 'param3', header: 'Param 3'}},
    { label: 'Param 4', value: { field: 'param4', header: 'Param 4'}},
    { label: 'Param 5', value: { field: 'param5', header: 'Param 5'}},
    { label: 'Param 6', value: { field: 'param6', header: 'Param 6'}},
    { label: 'Param 7', value: { field: 'param7', header: 'Param 7'}},
    { label: 'Param 8', value: { field: 'param8', header: 'Param 8'}},
    { label: 'Param 9', value: { field: 'param9', header: 'Param 9'}},
    { label: 'Param 10', value: { field: 'param10', header: 'Param 10'}}
];