export const testScriptsColumns: any[] = [
    { label: 'ID', value: { field: 'id', header: 'ID'}},
    { label: 'Test Case ID', value: { field: 'testCaseID', header: 'Test Case ID'}},
    { label: 'TC_StepID', value: { field: 'tc_stepID', header: 'TC_StepID'}},
    { label: 'TestScript Name', value: { field: 'testScriptName', header: 'TestScript Name'}},
    { label: 'Function Description', value: { field: 'functionDescription', header: 'Function Description'}},
    { label: 'Function Name', value: { field: 'functionName', header: 'Function Name'}},
    { label: 'Run', value: { field: 'run', header: 'Run'}},
    { label: 'Param 1', value: { field: 'param1', header: 'Param 1'}},
    { label: 'Param 2', value: { field: 'param2', header: 'Param 2'}},
    { label: 'Param 3', value: { field: 'param3', header: 'Param 3'}},
    { label: 'Param 4', value: { field: 'param4', header: 'Param 4'}},
    { label: 'Param 5', value: { field: 'param5', header: 'Param 5'}},
    { label: 'Param 6', value: { field: 'param6', header: 'Param 6'}},
    { label: 'Param 7', value: { field: 'param7', header: 'Param 7'}},
    { label: 'Param 8', value: { field: 'param8', header: 'Param 8'}},
    { label: 'Param 9', value: { field: 'param9', header: 'Param 9'}},
    { label: 'Param 10', value: { field: 'param10', header: 'Param 10'}},
    { label: 'Param 11', value: { field: 'param11', header: 'Param 11'}},
    { label: 'Param 12', value: { field: 'param12', header: 'Param 12'}},
    { label: 'Param 13', value: { field: 'param13', header: 'Param 13'}},
    { label: 'Param 14', value: { field: 'param14', header: 'Param 14'}},
    { label: 'Param 15', value: { field: 'param15', header: 'Param 15'}},
    { label: 'Param 16', value: { field: 'param16', header: 'Param 16'}},
    { label: 'Param 17', value: { field: 'param17', header: 'Param 17'}},
    { label: 'Param 18', value: { field: 'param18', header: 'Param 18'}},
    { label: 'Param 19', value: { field: 'param19', header: 'Param 19'}},
    { label: 'Param 20', value: { field: 'param20', header: 'Param 20'}},
    { label: 'Param 21', value: { field: 'param21', header: 'Param 21'}},
    { label: 'Param 22', value: { field: 'param22', header: 'Param 22'}},
    { label: 'Param 23', value: { field: 'param23', header: 'Param 23'}},
    { label: 'Param 24', value: { field: 'param24', header: 'Param 24'}},
    { label: 'Param 25', value: { field: 'param25', header: 'Param 25'}},
    { label: 'Param 26', value: { field: 'param26', header: 'Param 26'}},
    { label: 'Param 27', value: { field: 'param27', header: 'Param 27'}},
    { label: 'Param 28', value: { field: 'param28', header: 'Param 28'}},
    { label: 'Param 29', value: { field: 'param29', header: 'Param 29'}},
    { label: 'Param 30', value: { field: 'param30', header: 'Param 30'}},
    { label: 'Param 31', value: { field: 'param31', header: 'Param 31'}},
    { label: 'Param 32', value: { field: 'param32', header: 'Param 32'}},
    { label: 'Param 33', value: { field: 'param33', header: 'Param 33'}},
    { label: 'Param 34', value: { field: 'param34', header: 'Param 34'}},
    { label: 'Param 35', value: { field: 'param35', header: 'Param 35'}},
    { label: 'Param 36', value: { field: 'param36', header: 'Param 36'}},
    { label: 'Param 37', value: { field: 'param37', header: 'Param 37'}},
    { label: 'Param 38', value: { field: 'param38', header: 'Param 38'}},
    { label: 'Param 39', value: { field: 'param39', header: 'Param 39'}},
    { label: 'Param 40', value: { field: 'param40', header: 'Param 40'}},
    { label: 'Param 41', value: { field: 'param41', header: 'Param 41'}},
    { label: 'Param 42', value: { field: 'param42', header: 'Param 42'}},
    { label: 'Param 43', value: { field: 'param43', header: 'Param 43'}},
    { label: 'Param 44', value: { field: 'param44', header: 'Param 44'}},
    { label: 'Param 45', value: { field: 'param45', header: 'Param 45'}},
    { label: 'Param 46', value: { field: 'param46', header: 'Param 46'}},
    { label: 'Param 47', value: { field: 'param47', header: 'Param 47'}},
    { label: 'Param 48', value: { field: 'param48', header: 'Param 48'}},
    { label: 'Param 49', value: { field: 'param49', header: 'Param 49'}},
    { label: 'Param 50', value: { field: 'param50', header: 'Param 50'}},
    { label: 'Param 51', value: { field: 'param51', header: 'Param 51'}},
    { label: 'Param 52', value: { field: 'param52', header: 'Param 52'}},
    { label: 'Param 53', value: { field: 'param53', header: 'Param 53'}},
    { label: 'Param 54', value: { field: 'param54', header: 'Param 54'}},
    { label: 'Param 55', value: { field: 'param55', header: 'Param 55'}},
    { label: 'Param 56', value: { field: 'param56', header: 'Param 56'}},
    { label: 'Param 57', value: { field: 'param57', header: 'Param 57'}},
    { label: 'Param 58', value: { field: 'param58', header: 'Param 58'}},
    { label: 'Param 59', value: { field: 'param59', header: 'Param 59'}},
    { label: 'Param 60', value: { field: 'param60', header: 'Param 60'}},
    { label: 'Param 61', value: { field: 'param61', header: 'Param 61'}},
    { label: 'Param 62', value: { field: 'param62', header: 'Param 62'}},
    { label: 'Param 63', value: { field: 'param63', header: 'Param 63'}},
    { label: 'Param 64', value: { field: 'param64', header: 'Param 64'}},
    { label: 'Param 65', value: { field: 'param65', header: 'Param 65'}},
    { label: 'Param 66', value: { field: 'param66', header: 'Param 66'}},
    { label: 'Param 67', value: { field: 'param67', header: 'Param 67'}},
    { label: 'Param 68', value: { field: 'param68', header: 'Param 68'}},
    { label: 'Param 69', value: { field: 'param69', header: 'Param 69'}},
    { label: 'Param 70', value: { field: 'param70', header: 'Param 70'}},
    { label: 'Param 71', value: { field: 'param71', header: 'Param 71'}},
    { label: 'Param 72', value: { field: 'param72', header: 'Param 72'}},
    { label: 'Param 73', value: { field: 'param73', header: 'Param 73'}},
    { label: 'Param 74', value: { field: 'param74', header: 'Param 74'}},
    { label: 'Param 75', value: { field: 'param75', header: 'Param 75'}},
    { label: 'Param 76', value: { field: 'param76', header: 'Param 76'}},
    { label: 'Param 77', value: { field: 'param77', header: 'Param 77'}},
    { label: 'Param 78', value: { field: 'param78', header: 'Param 78'}},
    { label: 'Param 79', value: { field: 'param79', header: 'Param 79'}},
    { label: 'Param 80', value: { field: 'param80', header: 'Param 80'}},
    { label: 'Param 81', value: { field: 'param81', header: 'Param 81'}},
    { label: 'Param 82', value: { field: 'param82', header: 'Param 82'}},
    { label: 'Param 83', value: { field: 'param83', header: 'Param 83'}},
    { label: 'Param 84', value: { field: 'param84', header: 'Param 84'}},
    { label: 'Param 85', value: { field: 'param85', header: 'Param 85'}},
    { label: 'Param 86', value: { field: 'param86', header: 'Param 86'}},
    { label: 'Param 87', value: { field: 'param87', header: 'Param 87'}},
    { label: 'Param 88', value: { field: 'param88', header: 'Param 88'}},
    { label: 'Param 89', value: { field: 'param89', header: 'Param 89'}},
    { label: 'Param 90', value: { field: 'param90', header: 'Param 90'}},
    { label: 'Param 91', value: { field: 'param91', header: 'Param 91'}},
    { label: 'Param 92', value: { field: 'param92', header: 'Param 92'}},
    { label: 'Param 93', value: { field: 'param93', header: 'Param 93'}},
    { label: 'Param 94', value: { field: 'param94', header: 'Param 94'}},
    { label: 'Param 95', value: { field: 'param95', header: 'Param 95'}},
    { label: 'Param 96', value: { field: 'param96', header: 'Param 96'}},
    { label: 'Param 97', value: { field: 'param97', header: 'Param 97'}},
    { label: 'Param 98', value: { field: 'param98', header: 'Param 98'}},
    { label: 'Param 99', value: { field: 'param99', header: 'Param 99'}},
    { label: 'Param 100', value: { field: 'param100', header: 'Param 100'}},
    { label: 'Module', value: { field: 'module', header: 'Module'}},
    { label: 'Status ID', value: { field: 'statusId', header: 'Status ID'}},
    { label: 'Cud Status ID', value: { field: 'cudStatusID', header: 'Cud Status ID'}},
    { label: 'IsLocked', value: { field: 'isLocked', header: 'IsLocked'}},
    { label: 'Locked By User', value: { field: 'lockedByUser', header: 'Locked By User'}},
    { label: 'Created On', value: { field: 'createdOn', header: 'Created On'}},
    { label: 'Updated On', value: { field: 'updatedOn', header: 'Updated On'}},
    { label: 'User ID', value: { field: 'userId', header: 'User ID'}},
    { label: 'Actions', value: { field: 'actions', header: 'Actions'} }
];